### ISSUE TITLE
Battle for Mt Hyjal Lua error

### ISSUE THREAD

**Issue by drakkon222** [DeadlyBossMods/DBM-BCVanilla#10]
Message: Interface\AddOns\DBM-Hyjal\WaveTimers.lua:36: attempt to index field '?' (a nil value)
Time: Mon Nov  2 14:49:29 2020
Count: 2
Stack: Interface\AddOns\DBM-Hyjal\WaveTimers.lua:36: attempt to index field '?' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\DBM-Hyjal\WaveTimers.lua"]:36: in function `handler'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:857: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:844>

**Comment by Molkree** [comment]
This is fixed with latest release.
