### ISSUE TITLE
2 error in Hydross the Unstable on pull

### ISSUE THREAD

**Issue by milotic** [DeadlyBossMods/DBM-BCVanilla#11]
**Describe the bug**

pull and happen this: 

![WoWScrnShot_110920_202020](https://user-images.githubusercontent.com/1099848/98619836-a364df80-22c9-11eb-8c24-3ad7d42854f0.jpg)

rev: DBM-Outlands-r677.zip

**Comment by QartemisT** [comment]
Resolved in commit.
