### ISSUE TITLE
DBM classic error

### ISSUE THREAD

**Issue by strickland** [DeadlyBossMods/DBM-BCVanilla#2]
Date: 2019-08-31 23:35:23
ID: 1
Error occured in: Global
Count: 1
Message: Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceComm-3.0".
Debug:
   [C]: ?
   ...\Combuctor\common\libs\AceAddon-3.0\AceAddon-3.0.lua:189: EmbedLibrary()
   ...\Combuctor\common\libs\AceAddon-3.0\AceAddon-3.0.lua:171: EmbedLibraries()
   ...ddOns\DBM-Core\Libs\ThreatClassic-1.0\ThreatBoot.lua:20: in main chunk
Locals:
(*temporary) = "Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceComm-3.0"."

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.2
  ATTClassic, v0.0.8
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  Combuctor, v8.2.2
  DBMCore, v1.13.4
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=2ea)

**Comment by strickland** [comment]
Also please where can I find the dungeon package in the twitch client, I must install mods in the twitch clients itself due to restriction to downloading from the browser.

**Comment by MysticalOS** [comment]
this is already fixed in newest version. also there is no dungeon pack because EVERYTHING you need for classic wow, is built in
