### ISSUE TITLE
Error on Hearthstone - Vanilla (HC Servers)

### ISSUE THREAD

**Issue by Wyr3d** [DeadlyBossMods/DBM-BCVanilla#34]
Hearthed to Bloodhoof from Thunderbluff coz didn't wanna walk back. This popped up on spawning in Bloodhoof:

Date: 2023-08-25 23:00:01
ID: 3
Error occured in: Global
Count: 1
Message: ...AddOns/DBM-Core/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua line 374:
   LibDBIcon-1.0: Object 'Deathlog' is already registered.
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: error()
   [string "@Interface/AddOns/DBM-Core/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua"]:374: Register()
   [string "@Interface/AddOns/Deathlog/deathlog.lua"]:59:
      Interface/AddOns/Deathlog/deathlog.lua:57
   [string "@Interface/AddOns/Deathlog/deathlog.lua"]:110:
      Interface/AddOns/Deathlog/deathlog.lua:108
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v1.13.6652 (SwimmingSeadragon)
  AccountantClassic, vv2.12.26
  AllTheThings, vDF-3.5.6-hotfix-2
  Armory, vv1.11.2
  ButtonForge, v1.0.19-classic-era
  DBMCore, v0c953d2
  DBMStatusBarTimers, v0c953d2
  DBMVPVEM, ve153e73
  Deathlog, v0.1.1
  ExtendedMapZoneInfoForClassic, v1.5
  GatherMate2, v1.47-classic
  Grail, v121
  GrailNPCs, v27178
  GrailNPCsenUS, v33302
  GrailQuests, v27178
  GrailQuestsenUS, v33302
  GrailReputations, v007
  GrailWhen, v003
  HandyNotes, vv1.6.16
  IcyVeinsStats, vJuly 17th 2023
  LetMeCast, v1.3
  SlideBar, v<%version%> (<%codename%>)
  Spy, v1.2.4
  TradeSkillMaster, vv4.13.11
  TradeSkillMasterAppHelper, vv4.13
  Wholly, v089
  WIM, v3.10.15
  BlizRuntimeLib_enUS v1.14.4.11404 <none>
  (ck=2e1)

**Comment by QartemisT** [comment]
This is caused by the "Deadlog" addon, not us.

The reason we are blamed in the stacktrace, is because we were the first addon to load the library. Please report the issue over to there :)

**Comment by Wyr3d** [comment]
No worries. I figured it had to do with Deathlog, just wasn't sure if it was on both ends or just there
